import type { Metadata } from 'next'
import StyledComponentsRegistry from '@/lib/antd.registry'
import TopMenuComponent from './component/top.menu'
import { Layout } from 'antd'
import { Footer } from 'antd/es/layout/layout'
import ChatBoxModule from './component/chat.box'


export const metadata: Metadata = {
  title: 'SLM GLOBAL',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link
          rel="apple-touch-icon"
          href="/apple-icon?<generated>"
          type="image/<generated>"
          sizes="<generated>"
        />
        <link rel="icon" href="/favicon.ico" sizes="any" />

      </head>
      <body style={{ margin: 0, padding: 0 }}>

        <StyledComponentsRegistry>
          <Layout>
            <TopMenuComponent />
            <Layout style={{ marginTop: '116px' }}>
              {children}
            </Layout>
            <Footer style={{ textAlign: 'center' }}>SLMGLOBAL©2023</Footer>
          </Layout>

        </StyledComponentsRegistry>

      </body>
    </html>
  )
}
